SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
SET(CMAKE_ASM_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_RANLIB x86_64-w64-mingw32-ranlib)
SET(CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS clang-scan-deps)

SET(CMAKE_FIND_ROOT_PATH /github/home/opt)
SET(CMAKE_SYSROOT /github/home/opt)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
