name: Cache GCC With posix Toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: "toolchain"
        required: false
        default: "gcc-posix-x86_64"
        type: choice
        options:
        - gcc-posix-x86_64
        - gcc-posix-x86_64_v3  
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git unzip p7zip curl jq
      
      - name: Setting top_dir env
        run: |
          echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      
      - name: Cache gcc-posix-x86_64 cache
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64' }}
        uses: actions/cache@main
        id: gcc-posix-x86_64
        with:
          path: ${{ env.top_dir }}/cross
          key: gcc-x86_64-ucrt

      - name: Cache rust-x86_64 cache
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64' }}
        uses: actions/cache@main
        id: rust-x86_64
        with:
          path: ${{ env.top_dir }}/rust
          key: rust-x86_64

      - name: Cache gcc-posix-x86_64_v3 cache
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64_v3' }}
        uses: actions/cache@main
        id: gcc-posix-x86_64_v3
        with:
          path: ${{ env.top_dir }}/cross
          key: gcc-x86_64_v3-ucrt
      
      - name: Cache rust-x86_64_v3 cache
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64_v3' }}
        uses: actions/cache@main
        id: rust-x86_64_v3
        with:
          path: ${{ env.top_dir }}/rust
          key: rust-x86_64_v3

      - name: Setup gcc-posix-x86_64 Toolchain
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64' && steps.gcc-posix-x86_64.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-gcc-posix-latest-ucrt-x86_64.tar.xz
            tar -xvf cross*.tar.xz
            find cross/x86_64-w64-mingw32/lib -type f -name "*.la" -print0 | xargs -0 -I {} rm {}
            find cross/x86_64-w64-mingw32/lib -type f -name "*.dll.a" -print0 | xargs -0 -I {} rm {}
            rm cross*.tar.xz
          fi

      - name: Setup rust-x86_64 Toolchain
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64' && steps.rust-x86_64.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "rust" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/rust-x86_64-latest.7z
            7z x rust*.7z
            rm rust*.7z
          fi

      - name: Setup gcc-posix-x86_64_v3 Toolchain
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64_v3' && steps.gcc-posix-x86_64_v3.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-gcc-posix-latest-ucrt-x86_64_v3.tar.xz
            tar -xvf cross*.tar.xz
            find cross/x86_64-w64-mingw32/lib -type f -name "*.la" -print0 | xargs -0 -I {} rm {}
            find cross/x86_64-w64-mingw32/lib -type f -name "*.dll.a" -print0 | xargs -0 -I {} rm {}
            rm cross*.tar.xz
          fi

      - name: Setup rust-x86_64_v3 Toolchain
        if: ${{ inputs.toolchain == 'gcc-posix-x86_64_v3' && steps.rust-x86_64_v3.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "rust" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/rust-x86_64_v3-latest.7z
            7z x rust*.7z
            rm rust*.7z
          fi

