name: Cache LLVM-clang Toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: "toolchain"
        required: false
        default: "llvm-clang-x86_64"
        type: choice
        options:
        - llvm-clang-x86_64
        - llvm-clang-x86_64_v3
        - llvm-mingw
        - rust
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git unzip p7zip curl jq
          
      - name: Setting top_dir env
        run: |
           echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      
      - name: Loading llvm-clang-x86_64 cache
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64' }}
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/cross
          key: llvm-clang-x86_64-ucrt-${{ github.run_id }}
          restore-keys: |
            llvm-clang-x86_64-ucrt-

      - name: Loading llvm-clang-x86_64_v3 cache
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64_v3' }}
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/cross
          key: llvm-clang-x86_64_v3-ucrt-${{ github.run_id }}
          restore-keys: |
            llvm-clang-x86_64_v3-ucrt-

      - name: Loading llvm-mingw cache
        if: ${{ inputs.toolchain == 'llvm-mingw' }}
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/cross
          key: llvm-clang-x86_64-ucrt-${{ github.run_id }}
          restore-keys: |
            llvm-clang-x86_64-ucrt-

      - name: Loading rust cache
        if: ${{ inputs.toolchain == 'rust' }}
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/rust
          key: rust-${{ github.run_id }}
          restore-keys: |
            rust-

      - name: Setup llvm-clang-x86_64 Toolchain
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/llvm-clang-latest-ucrt-x86_64.7z
            7z x llvm*.7z
            rm llvm*.7z
          fi

      - name: Setup llvm-clang-x86_64_v3 Toolchain
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64_v3' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/llvm-clang-latest-ucrt-x86_64_v3.7z
            7z x llvm*.7z
            rm llvm*.7z
          fi

      - name: Setup llvm-mingw Toolchain
        if: ${{ inputs.toolchain == 'llvm-mingw' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.7z
            7z x cross*.7z
            find cross/x86_64-w64-mingw32/lib -maxdepth 1 -type f -name "*.dll.a" -print0 | xargs -0 -I {} rm {}
            rm cross*.7z
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-as
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-c++
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-clang
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-clang++
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-g++
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-gcc
            sed -i 's/$FLAGS "$@"/"$@" $FLAGS/' cross/bin/x86_64-w64-mingw32-ld
          fi

      - name: Setup Rust Toolchain
        if: ${{ inputs.toolchain == 'rust' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "rust" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/rustup-latest.7z
            7z x rustup*.7z
            rm rustup*.7z
          fi 

      - name: Saving llvm-clang-x86_64 cache
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64' }}
        uses: actions/cache/save@main
        with:
          path: ${{ env.top_dir }}/cross
          key: llvm-clang-x86_64-ucrt-${{ github.run_id }}

      - name: Saving llvm-clang-x86_64_v3 cache
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64_v3' }}
        uses: actions/cache/save@main
        with:
          path: ${{ env.top_dir }}/cross
          key: llvm-clang-x86_64_v3-ucrt-${{ github.run_id }}

      - name: Saving llvm-mingw cache
        if: ${{ inputs.toolchain == 'llvm-mingw' }}
        uses: actions/cache/save@main
        with:
          path: ${{ env.top_dir }}/cross
          key: llvm-clang-x86_64-ucrt-${{ github.run_id }}      

      - name: Saving Rust cache
        if: ${{ inputs.toolchain == 'rust' }}
        uses: actions/cache/save@main
        with:
          path: ${{ env.top_dir }}/rust
          key: rust-${{ github.run_id }}
