name: Cache llvm-clang Toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: "toolchain"
        required: false
        default: "llvm-clang-x86_64"
        type: choice
        options:
        - llvm-clang-x86_64
        - llvm-clang-x86_64_v3
        - llvm-clang-pgo-x86_64
        - llvm-clang-pgo-x86_64_v3        
        - llvm-mingw
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:                   
      - name: Setting top_dir env
        run: |
           echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      
      - name: Cache llvm-clang-x86_64
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64' }}
        uses: actions/cache@main
        id: llvm-clang-x86_64-ucrt
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-x86_64-ucrt

      - name: Cache llvm-clang-x86_64_v3
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64_v3' }}
        uses: actions/cache@main
        id: llvm-clang-x86_64_v3-ucrt
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-x86_64_v3-ucrt

      - name: Cache llvm-clang-pgo-x86_64
        if: ${{ inputs.toolchain == 'llvm-clang-pgo-x86_64' }}
        uses: actions/cache@main
        id: llvm-clang-pgo-x86_64-ucrt
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-x86_64-ucrt

      - name: Cache llvm-clang-pgo-x86_64_v3
        if: ${{ inputs.toolchain == 'llvm-clang-pgo-x86_64_v3' }}
        uses: actions/cache@main
        id: llvm-clang-pgo-x86_64_v3-ucrt
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-x86_64_v3-ucrt

      - name: Cache llvm-mingw
        if: ${{ inputs.toolchain == 'llvm-mingw' }}
        uses: actions/cache@main
        id: llvm-mingw
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-x86_64-ucrt

      - name: Cache rust
        uses: actions/cache@main
        id: rust
        with:
          path: ${{ env.top_dir }}/rust
          key: rust

      - name: Setup llvm-clang-x86_64 Toolchain
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64' && steps.llvm-clang-x86_64-ucrt.outputs.cache-hit != 'true' }} 
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-clang-latest-ucrt-x86_64.7z
            7z x llvm*.7z
            rm llvm*.7z
          fi

      - name: Setup llvm-clang-x86_64_v3 Toolchain
        if: ${{ inputs.toolchain == 'llvm-clang-x86_64_v3' && steps.llvm-clang-x86_64_v3-ucrt.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-clang-latest-ucrt-x86_64_v3.7z
            7z x llvm*.7z
            rm llvm*.7z
          fi

      - name: Setup llvm-clang-pgo-x86_64 Toolchain
        if: ${{ inputs.toolchain == 'llvm-clang-pgo-x86_64' && steps.llvm-clang-pgo-x86_64-ucrt.outputs.cache-hit != 'true' }} 
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-clang-pgo-latest-ucrt-x86_64.7z
            7z x cross*.7z
            rm cross*.7z
          fi

      - name: Setup llvm-clang-pgo-x86_64_v3 Toolchain
        if: ${{ inputs.toolchain == 'llvm-clang-pgo-x86_64_v3' && steps.llvm-clang-pgo-x86_64_v3-ucrt.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-clang-pgo-latest-ucrt-x86_64_v3.7z
            7z x cross*.7z
            rm cross*.7z
          fi

      - name: Setup llvm-mingw Toolchain
        if: ${{ inputs.toolchain == 'llvm-mingw' && steps.llvm-mingw.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.tar.xz
            tar -xvf cross*.tar.xz
            find cross/x86_64-w64-mingw32/lib -maxdepth 1 -type f -name "*.dll.a" -print0 | xargs -0 -I {} rm {}
            rm cross*.tar.xz
          fi

      - name: Setup Rust Toolchain
        if: ${{ steps.rust.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "rust" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/rust-latest.7z
            7z x rust*.7z
            rm rust*.7z
          fi
