name: cache-clang
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: "toolchain"
        required: false
        default: "llvm-archlinux"
        type: choice
        options:
        - llvm-archlinux
        - llvm-mingw 
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git unzip p7zip curl jq
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
      - name: Setting top_dir env
        run: |
           echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      - name: Loading clang cache
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-${{ github.run_id }}
          restore-keys: |
            clang-
            
      - name: Setup Clang Toolchain
        if: ${{ inputs.toolchain =='llvm-archlinux' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/llvm-archlinux-2023-12-29-ucrt-x86_64.7z
            7z x llvm*.7z
            rm llvm*.7z
          fi

      - name: Setup Clang Toolchain
        if: ${{ inputs.toolchain =='llvm-mingw' }}
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "cross/bin" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-mingw-2023-12-30-ucrt-x86_64.7z
            7z x cross*.7z
            rm cross*.7z
            find cross/x86_64-w64-mingw32/lib -maxdepth 1 -type f -name "*.dll.a" -print0 | xargs -0 -I {} rm {}
          fi

      - name: Saving clang cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-${{ github.run_id }}
