name: cache-rust
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git yasm nasm ninja cmake python-pip curl python-cairo unzip p7zip curl jq
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
      - name: Setting top_dir env
        run: |
           echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      - name: Loading gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/rust
          key: rust-${{ github.run_id }}
          restore-keys: |
            rust-
            
      - name: Setup Rust Toolchain
        run: |
          cd ${{ env.top_dir }}
          if [[ ! -d "rust" ]]; then
            curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/rustup-20230723.7z
            7z x rustup*.7z
            rm rustup*.7z
          fi  

      - name: Saving Rust cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ env.top_dir }}/rust
          key: rust-${{ github.run_id }}
