name: cross-gcc-mcf
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed git gyp cvs mercurial subversion ninja cmake ragel yasm nasm asciidoc enca gperf zip unzip p7zip xz mingw-w64-gcc gcc-multilib clang python-pip curl jq lib32-glib2 wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema meson
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
          
      - uses: actions/checkout@main
      - name: Loading gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-mcf-${{ github.run_id }}
          restore-keys: |
            cross-gcc-mcf-
            
      - name: Building toolchain
        run: |
          PWD=$(pwd)
          if [[ ! "$(ls -A $PWD/cross/bin)" ]]; then
            chmod +x ./cross-gcc-mcf.sh
            ./cross-gcc-mcf.sh
          fi  

      - name: Packaging toolchain
        run: |
          rm -f cross/mingw
          rm -rf cross/share
          7z a cross-gcc-mcf.7z cross/*

      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./release-package.sh
          ./release-package.sh cross-gcc-mcf.7z

      - name: Saving gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-mcf-${{ github.run_id }}
