name: Delete old releases

on:
#  schedule:
#  - cron: '08 12 * * MON'
  workflow_dispatch:
     
jobs:
  prune:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@main
      - uses: freenet-actions/delete-old-releases@main
        with:
          #prefix: '20'  # Delete all releases starting with "20".
          max-age: 'P1W'      # Delete all releases older than one week.
          delete-tags: true
          token: '${{ github.token }}'
