name: libmysofa
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:

jobs:
  libmysofa:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm docker
          sudo pacman -S --noconfirm --needed git ninja cmake yasm nasm unzip p7zip python-pip python-cairo curl jq wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema meson
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
      - name: Add builder user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      - name: Setting top_dir env
        run: |
          echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV         
      - name: Checkout
        uses: actions/checkout@main
      - name: Setting makepkg etc
        run: |
          sudo cp pacman-config/makepkg_cross.conf /etc
          sudo cp pacman-config/makepkg-cross /usr/local/bin
          sudo rm /usr/lib/libz.a
      - name: Loading cross gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ env.top_dir }}/cross
          key: cross-gcc-mcf-${{ github.run_id }}
          restore-keys: |
            cross-gcc-mcf-
      - name: Build
        env:
          C_INCLUDE_PATH: /github/home/opt/include
          CPLUS_INCLUDE_PATH: /github/home/opt/include
          LIBRARY_PATH: /github/home/opt/lib
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev/zlib-dev-1.2.13-1-x86_64.pkg.tar.zst      
          pacman -U *.zst --noconfirm                   
          sudo chmod 777 -R ${{ env.top_dir }}
          sudo chmod 777 -R .
          cd libmysofa-dev
          PKG_CONFIG_PATH=/github/home/opt/lib/pkgconfig
          sudo -H -u builder makepkg-cross -sC --noconfirm 
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}    
        run: |
          ./release-dev.sh libmysofa-dev libmysofa-dev
