name: libplacebo
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      build_target:
        description: "Build target"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - x86_64_v3

jobs:
  libplacebo:
    runs-on: ubuntu-latest
    env:
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }} 
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main      
      - name: Add builder user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          sudo cp pacman-config/makepkg_cross.conf /etc
          sudo cp pacman-config/makepkg-cross /usr/bin
      - name: Setting top_dir env
        run: echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      - name: Loading clang-${{ inputs.build_target }} cache
        uses: actions/cache@main
        with:
          path: ${{ env.top_dir }}/cross
          key: clang-${{ inputs.build_target }}-ucrt
      - name: Build
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/lcms2-dev-2.16-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/libdovi-dev-3.3.0-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/libjpeg-dev-3.0.3-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/shaderc-dev-2024.1-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/spirv-cross-dev-1.3.261.1-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/vulkan-dev-1.3.280.0-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/xxhash-dev-0.8.2-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-clang-$BIT/zlib-dev-2.1.6-1-x86_64.pkg.tar.zst
          pacman -U *.zst --noconfirm 
          sudo chmod 777 -R ${{ env.top_dir }} .
          cd libplacebo-dev; sudo -H -u builder makepkg-cross -sLf
      - name: Release    
        run: ./release-dev.sh libplacebo-dev libplacebo-dev
