name: libplacebo
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      compiler:
        description: "Compiler"
        required: false
        default: "clang"
        type: choice
        options:
        - clang
        - gcc      
      build_target:
        description: "Build target"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - x86_64_v3

jobs:
  libdovi:
    runs-on: ubuntu-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }} 
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main      
      - name: Add builder user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          sudo cp pacman-config/makepkg_cross_$COMPILER.conf /etc
          sudo cp pacman-config/makepkg-cross-$COMPILER /usr/bin
      - name: Setting top_dir env
        run: echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      - name: Loading ${{ inputs.compiler }}-${{ inputs.build_target }} cache
        uses: actions/cache@main
        with:
          path: ${{ env.top_dir }}/cross
          key: ${{ inputs.compiler }}-${{ inputs.build_target }}-ucrt
      - name: Setup rust toolchain
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/rust-for-win7-1.77.2.7z
          7z x rust-for-win7-1.77.2.7z -o${{ env.top_dir }}
          rm rust-for-win7-1.77.2.7z
      - name: Build
        run: |
          sudo chmod 777 -R ${{ env.top_dir }} .
          cd libdovi-dev; sudo -H -u builder makepkg-cross-$COMPILER -sLf    
      - name: Release    
        run: ./release-dev.sh libdovi-dev libdovi-dev

  libplacebo:
    needs: [libdovi]
    runs-on: ubuntu-latest
    env:
      COMPILER: ${{ inputs.compiler }}
      BIT: ${{ inputs.build_target }}
      GH_TOKEN: ${{ secrets.BOT }}
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main      
      - name: Add builder user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          sudo cp pacman-config/makepkg_cross_$COMPILER.conf /etc
          sudo cp pacman-config/makepkg-cross-$COMPILER /usr/bin
      - name: Setting top_dir env
        run: echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
      - name: Loading ${{ inputs.compiler }}-${{ inputs.build_target }} cache
        uses: actions/cache@main
        with:
          path: ${{ env.top_dir }}/cross
          key: ${{ inputs.compiler }}-${{ inputs.build_target }}-ucrt
      - name: Build
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/lcms2-dev-2.16-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libdovi-dev-3.3.1-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/libjpeg-dev-3.0.3-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/shaderc-dev-2024.1-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/spirv-cross-dev-1.3.261.1-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/vulkan-dev-1.3.290.0-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/xxhash-dev-0.8.2-1-x86_64.pkg.tar.zst
          curl -OL https://github.com/${{ github.repository }}/releases/download/dev-$COMPILER-$BIT/zlib-dev-2.2.1-1-x86_64.pkg.tar.zst
          pacman -U *.zst --noconfirm 
          sudo chmod 777 -R ${{ env.top_dir }} .
          cd libplacebo-dev; sudo -H -u builder makepkg-cross-$COMPILER -sLf
      - name: Release    
        run: ./release-dev.sh libplacebo-dev libplacebo-dev
